package com.lingrui.crm.settings.mapper;

import com.lingrui.crm.settings.domain.DictValue;

import java.util.List;

public interface DictValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Sat Jun 18 20:49:33 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Sat Jun 18 20:49:33 CST 2022
     */
    int insert(DictValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Sat Jun 18 20:49:33 CST 2022
     */
    int insertSelective(DictValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Sat Jun 18 20:49:33 CST 2022
     */
    DictValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Sat Jun 18 20:49:33 CST 2022
     */
    int updateByPrimaryKeySelective(DictValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Sat Jun 18 20:49:33 CST 2022
     */
    int updateByPrimaryKey(DictValue record);

    /**
     * @param :
     * @return List<DictValue>
     * @author xulingrui
     * @description TODO
     * 获取所有字典值
     * @date 2022/6/18 23:16
     */
    List<DictValue> selectAllDictValue();

    /**
     * @param typeCode:
     * @return List<DictValue>
     * @author xulingrui
     * @description TODO
     * 根据字典类型编码，查询所有字典值的list
     * @date 2022/6/18 23:53
     */
    List<DictValue> selectDictValueByTypeCode(String typeCode);

    /**
     * @param dictValue:
     * @return int
     * @author xulingrui
     * @description TODO
     * 新增一条
     * @date 2022/6/19 00:00
     */
    int insertDictValue(DictValue dictValue);

    /**
     * @param dictValue:
     * @return int
     * @author xulingrui
     * @description TODO
     * 更新修改后的字典值
     * @date 2022/6/19 00:04
     */
    int updateDictValue(DictValue dictValue);

    /**
     * @param ids:
     * @return int
     * @author xulingrui
     * @description TODO
     * 根据id字符串数组删除字典值
     * @date 2022/6/20 08:50
     */
    int deleteDictValueByIds(String[] ids);

    /**
     * @param id:
     * @return DictValue
     * @author xulingrui
     * @description TODO
     * 根据id查字典值
     * @date 2022/6/21 10:45
     */
    DictValue selectDictValueById(String id);
}